    name: TeamWorkFlow
    on:
      push:
        branches:
          - main

  job: 
    integration-delivery: 
      runs-on: ubuntu-latest
      environment: Test
      container: 
        image: node
        steps: 
        name: Checkout Code
        uses: actions/checkout@v3

        name: Install Dependencies
        run: npm install